# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

services:
  - redis:5.0.7
  - mysql:8.0.19
  

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service


test:
  variables:
    NODE_ENV: test
    MYSQL_DATABASE: node_boilerplate_test
    MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    DB_NAME: node_boilerplate_test
  script:
    - npm install
    - npx sequelize-cli db:migrate
    - npm run test

