version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10
      - image: circleci/redis:5.0.7
      - image: circleci/mysql:8.0.19
        environment:
          MYSQL_DATABASE: node_boilerplate_test
          MYSQL_USER: root
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
jobs:
  build:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run: sudo npm install -g sequelize-cli
  test:
    environment:
      NODE_ENV: test
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npx sequelize-cli db:create
      - run: npx sequelize-cli db:migrate
      - run: npm run test