version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10
      - image: circleci/redis:5.0.7
      - image: circleci/mysql:8.0.19
        environment:
          MYSQL_DATABASE: node_boilerplate_test
          MYSQL_USER: groot
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
jobs:
  test:
    environment:
      NODE_ENV: test
      DB_NAME: ${MYSQL_DATABASE}
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npx sequelize-cli db:migrate
      - run: npm run test
  deploy:
    executor: node
    steps:
      - run:
          name: 'Deploy over SSH'
          command: |
            ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST "/home/ubuntu/node-projects/nodejs-boilerplate/deploy.sh"